/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz1;

/**
 *
 * @author Windows 10
 */
public class Kasir extends javax.swing.JFrame {

    /**
     * Creates new form Kasir
     */
    public Kasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Nama = new javax.swing.JLabel();
        Harga = new javax.swing.JLabel();
        Jumlah = new javax.swing.JLabel();
        Jharga = new javax.swing.JLabel();
        jbayar = new javax.swing.JLabel();
        jkembalian = new javax.swing.JLabel();
        pilihmenu = new javax.swing.JComboBox<>();
        isiharga = new javax.swing.JTextField();
        isijumlah = new javax.swing.JTextField();
        isitotal = new javax.swing.JTextField();
        isibayar = new javax.swing.JTextField();
        isikembalian = new javax.swing.JTextField();
        tombolhitung = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        tomboltotal = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz1/logo.png"))); // NOI18N

        judul1.setFont(new java.awt.Font("Elephant", 1, 30)); // NOI18N
        judul1.setForeground(new java.awt.Color(0, 102, 51));
        judul1.setText("STARBUCKS");

        judul2.setFont(new java.awt.Font("Elephant", 1, 30)); // NOI18N
        judul2.setForeground(new java.awt.Color(0, 102, 51));
        judul2.setText("COFFEE");

        slogan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        slogan.setText("Coffee that Inspires");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logo)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judul1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(judul2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(slogan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slogan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 101);

        jPanel2.setBackground(new java.awt.Color(0, 51, 0));

        Nama.setBackground(new java.awt.Color(255, 255, 255));
        Nama.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Nama.setForeground(new java.awt.Color(255, 255, 255));
        Nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nama.setText("Nama Barang    :");

        Harga.setBackground(new java.awt.Color(255, 255, 255));
        Harga.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Harga.setForeground(new java.awt.Color(255, 255, 255));
        Harga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Harga.setText("Harga Barang    :");

        Jumlah.setBackground(new java.awt.Color(255, 255, 255));
        Jumlah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jumlah.setForeground(new java.awt.Color(255, 255, 255));
        Jumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jumlah.setText("Jumlah Order    :");

        Jharga.setBackground(new java.awt.Color(255, 255, 255));
        Jharga.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Jharga.setForeground(new java.awt.Color(255, 255, 255));
        Jharga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jharga.setText("Jumlah Harga    :");

        jbayar.setBackground(new java.awt.Color(255, 255, 255));
        jbayar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbayar.setForeground(new java.awt.Color(255, 255, 255));
        jbayar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbayar.setText("Jumlah Bayar           :");

        jkembalian.setBackground(new java.awt.Color(255, 255, 255));
        jkembalian.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jkembalian.setForeground(new java.awt.Color(255, 255, 255));
        jkembalian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jkembalian.setText("Jumlah Kembalian    :");

        pilihmenu.setBackground(new java.awt.Color(0, 51, 0));
        pilihmenu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pilihmenu.setForeground(new java.awt.Color(255, 255, 255));
        pilihmenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih nama barang", "Caffe Americano", "Caramel Macchiato", "Salted Caramel latte", "Cappuccino", "Caffe Mocha", "Cold Brew" }));
        pilihmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihmenuActionPerformed(evt);
            }
        });

        isiharga.setBackground(new java.awt.Color(0, 51, 0));
        isiharga.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        isiharga.setForeground(new java.awt.Color(255, 255, 255));
        isiharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isihargaActionPerformed(evt);
            }
        });

        isijumlah.setBackground(new java.awt.Color(0, 51, 0));
        isijumlah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        isijumlah.setForeground(new java.awt.Color(255, 255, 255));
        isijumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isijumlahActionPerformed(evt);
            }
        });

        isitotal.setBackground(new java.awt.Color(0, 51, 0));
        isitotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        isitotal.setForeground(new java.awt.Color(255, 255, 255));
        isitotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isitotalActionPerformed(evt);
            }
        });

        isibayar.setBackground(new java.awt.Color(0, 51, 0));
        isibayar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        isibayar.setForeground(new java.awt.Color(255, 255, 255));
        isibayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isibayarActionPerformed(evt);
            }
        });

        isikembalian.setBackground(new java.awt.Color(0, 51, 0));
        isikembalian.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        isikembalian.setForeground(new java.awt.Color(255, 255, 255));
        isikembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isikembalianActionPerformed(evt);
            }
        });

        tombolhitung.setBackground(new java.awt.Color(255, 255, 51));
        tombolhitung.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tombolhitung.setText("Hitung");
        tombolhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolhitungActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(255, 0, 0));
        reset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        reset.setText("Batal");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        tomboltotal.setBackground(new java.awt.Color(255, 255, 51));
        tomboltotal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tomboltotal.setText("Hitung Total");
        tomboltotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboltotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(tombolhitung)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Jharga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(Harga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(isiharga, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilihmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isijumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isitotal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbayar)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(reset)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(isibayar)
                                    .addComponent(isikembalian)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tomboltotal)
                                .addGap(43, 43, 43)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilihmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isiharga, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isijumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jharga, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isitotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tombolhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isibayar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(isikembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                        .addContainerGap(92, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tomboltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 410, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isihargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isihargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isihargaActionPerformed

    private void isijumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isijumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isijumlahActionPerformed

    private void isitotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isitotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isitotalActionPerformed

    private void isibayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isibayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isibayarActionPerformed

    private void isikembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isikembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isikembalianActionPerformed

    private void tombolhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolhitungActionPerformed
        int jumlahbarang = Integer.parseInt(isijumlah.getText());
        int hargabarang = Integer.parseInt(isiharga.getText());
        isitotal.setText(Integer.toString(hargabarang*jumlahbarang));

    }//GEN-LAST:event_tombolhitungActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        isiharga.setText("");
        isijumlah.setText("");
        isitotal.setText("");
        isibayar.setText("");
        isikembalian.setText("");
        pilihmenu.setSelectedIndex(0);
    }//GEN-LAST:event_resetActionPerformed

    private void tomboltotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboltotalActionPerformed
        int jumlahbayar = Integer.parseInt(isibayar.getText());
        int jumlahharga = Integer.parseInt(isitotal.getText());
        if (jumlahbayar >= jumlahharga){
            isikembalian.setText(Integer.toString(jumlahbayar-jumlahharga));
        }
        else{
            isikembalian.setText("Uang Anda Kurang");
        }


    }//GEN-LAST:event_tomboltotalActionPerformed

    private void pilihmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihmenuActionPerformed
       String namabarang = (String)pilihmenu.getSelectedItem();
       switch (namabarang){
           case "Caffe Americano":
               isiharga.setText("43000");
               break;
           case "Caramel Macchiato":
               isiharga.setText("67000");
               break;
           case "Salted Caramel Latte":
               isiharga.setText("60000");
               break;
           case "Cappuccino":
               isiharga.setText("54000");
               break;
           case "Caffe Mocha":
               isiharga.setText("62000");
               break;
           case "Cold Brew":
               isiharga.setText("51000");
               break;
       }
    }//GEN-LAST:event_pilihmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Harga;
    private javax.swing.JLabel Jharga;
    private javax.swing.JLabel Jumlah;
    private javax.swing.JLabel Nama;
    private javax.swing.JTextField isibayar;
    private javax.swing.JTextField isiharga;
    private javax.swing.JTextField isijumlah;
    private javax.swing.JTextField isikembalian;
    private javax.swing.JTextField isitotal;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jbayar;
    private javax.swing.JLabel jkembalian;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> pilihmenu;
    private javax.swing.JButton reset;
    private javax.swing.JLabel slogan;
    private javax.swing.JButton tombolhitung;
    private javax.swing.JButton tomboltotal;
    // End of variables declaration//GEN-END:variables
}
